baseURL = 'https://doulacooperative.com/'
languageCode = 'en-us'
title = 'Rochester Doula Cooperative'
enableRobotsTXT = true


[build]
  writeStats = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.129.0"

[taxonomies]
  type = "types"

[permalinks]
  types = "/doulas/:slug/"

[[menu.main]]
  name = "About"
  pageRef = "/about-the-doula-cooperative"
  weight = 10
[[menu.main]]
  name = "Join"
  pageRef = "/join-the-doula-cooperative"
  weight = 20
[[menu.main]]
  name = "Contact"
  pageRef = "/contact-us"
  weight = 30
