baseURL = 'https://doulacooperative.com/'
languageCode = 'en-us'
title = 'Rochester Doula Cooperative'


[build]
  writeStats = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.129.0"

[taxonomies]
  type = "types"

[permalinks]
  types = "/doulas/:slug/"

enableRobotsTXT = true
