export const PROFILE_TAGS = [
  'Abortion Doula',
  'ASL Interpreter',
  'Babywearing Educator & Consultant',
  'Belly casting',
  'Birth Doula',
  'Birth Photographer',
  'Birth Photography',
  'Birth Planning',
  'Breastfeeding Consultant',
  'Breastfeeding Educator',
  'Breastmilk jewelry',
  'Breathing techniques',
  'Certified Body Ready Method® Pro',
  'Certified Lactation Counselor',
  'Certified VBAC Doula',
  'Childbirth Educator',
  'Chiropractor',
  'Doula Training',
  'Fertility Support',
  'Full Spectrum Doula',
  'Hospital-Grade Breast Pump Rentals',
  'Hypno-Doula',
  'Labor Acupuncture',
  'Lactation Support',
  'Massage Therapist',
  'Nesting Party Coordinator',
  'Parent education',
  'Pediatric Sleep Consultant',
  'Perinatal Loss Doula',
  'Placenta Encapsulation Services',
  'Placenta Encapsulation',
  'Placenta Services',
  'Placenta Specialist',
  'Postpartum Doula',
  'Postpartum nutrition coach',
  'Pre-Postnatal Yoga',
  'Pregnancy Acupuncture',
  'Pregnancy Bodywork',
  'Prenatal and Postnatal Yoga Instructor',
  'Prenatal Breastfeeding Class',
  'Reiki Healing',
  'Returning to Work Support Group',
  'Spinning Babies Aware Practitioner',
] as const;
