export const PROFILE_TAGS = [
  'Abortion Doula',
  'ASL Interpreter',
  'Babywearing Educator & Consultant',
  'Belly casting',
  'Birth Doula',
  'Birth Photography',
  'Birth Planning',
  'Breastfeeding Consultant',
  'Breastfeeding Educator',
  'Breastmilk jewelry',
  'Breathing techniques',
  'Certified Body Ready Method® Pro',
  'Certified Lactation Counselor',
  'Certified VBAC Doula',
  'Childbirth Educator',
  'Chiropractor',
  'Doula Training',
  'Fertility Support',
  'Full Spectrum Doula',
  'Hospital-Grade Breast Pump Rentals',
  'Hypno-Doula',
  'Lactation Support',
  'Massage Therapist',
  'Nesting Party Coordinator',
  'Parent education',
  'Pediatric Sleep Consultant',
  'Perinatal Acupuncture',
  'Perinatal Loss Doula',
  'Placenta Services',
  'Postpartum Doula',
  'Postpartum nutrition coach',
  'Pregnancy Bodywork',
  'Prenatal and Postnatal Yoga Instructor',
  'Prenatal Breastfeeding Class',
  'Reiki Healing',
  'Returning to Work Support Group',
  'Spinning Babies Aware Practitioner',
] as const;
